Fix nightly by installing earlier version of lief (#4198)
Summary:
Pull Request resolved: https://github.com/facebookresearch/faiss/pull/4198

1. pins lief due to `AttributeError: type object 'CLASS' has no attribute 'CLASS64'` (just set it to last passing nightly version)
2. pins mkl in gpu builds due to it trying to pull in 2024.2.2 which conflicts with 2023 in the libfaiss.

Added nightlies to make sure they pass https://github.com/facebookresearch/faiss/actions/runs/13422430425/job/37498020894. Not all passed: I'm not sure the `build-pull-request / Linux x86_64 GPU w/ cuVS nightlies (CUDA 12.4.0)` nightly is actually broken, but this unblocks the PR builds for now.

Reviewed By: junjieqi

Differential Revision: D69860604

fbshipit-source-id: 2da623c71b03c22d581b78655253a863fbafd3ed